### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Loppetier** [Scrut1ny/WebsiteLinksReference#1]
Hi Scrut1ny,

My name is Semih, and I am currently working on my bachelor’s thesis in the field of Information Systems. My research focuses on
creating a systematic ranking of websites in the Tor network.

I came across your repository,[V3_ONION_LINKS](https://github.com/Scrut1ny/V3_ONION_LINKS), and found it highly relevant to my research. Specifically, I am interested in extracting ligitimate Onion-links. Before using any data from the repository, I want to ensure that I comply with your guidelines.

Unfortunately, I couldn’t find clear licensing information in your repository. I’d like to kindly ask:

Under which license is the content of your repository provided?
Would it be permissible to use the data for academic purposes, such as conducting analyses or creating filtered lists?
Are there any specific conditions I should follow if I use the data?
I assure you that your repository will be properly cited in my work, and any additional licensing terms or acknowledgments you specify will be included.

Thank you for making this valuable resource available! I look forward to your response and hope for permission to use your repository.

Best regards,
Sem

**Comment by Scrut1ny** [comment]
Hi Semih,

Thanks for reaching out! My repository, V3_ONION_LINKS, doesn't have a formal license, but the data is freely available for public use. You’re welcome to use it for your research, and a citation would be appreciated, but there are no specific conditions or restrictions.
